# Global Configuration

# jwt configuration
jwt:
  signing-key: 'nginx'

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[nginx-web]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'mysql'
  oss-type: 'local'
  use-multipoint: false

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'nginx_web'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false

# local configuration
local:
  path: 'uploads/file'


#ssh configuration
ssh:
  private_key: "./resource/ssh/id_rsa"
  public_key: "./resource/ssh/id_rsa.pub"

nginx:
  config_path: "/etc/nginx/conf.d/"
  cert_path: "/etc/nginx/conf.d/cert/"